%{
/*
 * interp.y  –  Parser + executor for the coded assembly language
 *
 * USAGE
 *   bison  -d interp.y          →  interp.tab.c  interp.tab.h
 *   flex      interp.l          →  lex.yy.c
 *   gcc lex.yy.c interp.tab.c -o interp
 *   ./interp < coded.asm
 *
 * TWO-PHASE DESIGN
 *   Phase 1 (yyparse)  : every line of coded.asm is loaded into program[].
 *   Phase 2 (execute)  : a PC loop walks program[] and runs each instruction.
 *
 * This separation is necessary so that JMP / JMF can target any instruction
 * number, including ones that come BEFORE the current position.
 */

#include <stdio.h>
#include <stdlib.h>

/* ─── Opcodes (must match the compiler) ────────────────────────────────── */
#define ADD  1
#define MUL  2
#define SOU  3
#define DIV  4
#define COP  5
#define AFC  6
#define JMP  7
#define JMF  8
#define INF  9
#define SUP  10   /* 0xA */
#define EQU  11   /* 0xB */
#define PRI  12   /* 0xC */

/* ─── Memory model ─────────────────────────────────────────────────────── */
/*
 * Flat array that mirrors the compiler's memory layout:
 *   memory[0 .. 100]   user variables and constants
 *   memory[101 .. ]    temporaries (reused across statements)
 *
 * 10 000 cells is more than enough for any program generated by the compiler.
 */
#define MAX_MEM   10000
int memory[MAX_MEM];   /* zero-initialised by C */

/* ─── Instruction store ────────────────────────────────────────────────── */
/*
 * Each instruction has an opcode and up to three integer operands.
 * Unused operands are left as 0.
 *
 *  op   a    b    c
 *  AFC  dst  val  –     memory[dst]  =  val
 *  COP  dst  src  –     memory[dst]  =  memory[src]
 *  ADD  dst  x    y     memory[dst]  =  memory[x]  +  memory[y]
 *  SOU  dst  x    y     memory[dst]  =  memory[x]  -  memory[y]
 *  MUL  dst  x    y     memory[dst]  =  memory[x]  *  memory[y]
 *  DIV  dst  x    y     memory[dst]  =  memory[x]  /  memory[y]
 *  INF  dst  x    y     memory[dst]  =  (memory[x] <  memory[y]) ? 1 : 0
 *  SUP  dst  x    y     memory[dst]  =  (memory[x] >  memory[y]) ? 1 : 0
 *  EQU  dst  x    y     memory[dst]  =  (memory[x] == memory[y]) ? 1 : 0
 *  JMP  tgt  –    –     pc = tgt
 *  JMF  cnd  tgt  –     if memory[cnd] == 0  then  pc = tgt
 *  PRI  src  –    –     printf("%d\n", memory[src])
 */
#define MAX_INSTR 10000

typedef struct {
    int op;
    int a, b, c;
} Instruction;

Instruction program[MAX_INSTR];
int instr_count = 0;

/* ─── Helpers called from grammar actions ───────────────────────────────── */

/*
 * store2 / store3 / store4
 * Add one instruction to program[].  The suffix indicates how many integers
 * were on that line (opcode + 1, 2, or 3 operands).
 */
static void store2(int op, int a) {
    if (instr_count >= MAX_INSTR) { fprintf(stderr, "Program too large.\n"); exit(1); }
    program[instr_count].op = op;
    program[instr_count].a  = a;
    program[instr_count].b  = 0;
    program[instr_count].c  = 0;
    instr_count++;
}

static void store3(int op, int a, int b) {
    if (instr_count >= MAX_INSTR) { fprintf(stderr, "Program too large.\n"); exit(1); }
    program[instr_count].op = op;
    program[instr_count].a  = a;
    program[instr_count].b  = b;
    program[instr_count].c  = 0;
    instr_count++;
}

static void store4(int op, int a, int b, int c) {
    if (instr_count >= MAX_INSTR) { fprintf(stderr, "Program too large.\n"); exit(1); }
    program[instr_count].op = op;
    program[instr_count].a  = a;
    program[instr_count].b  = b;
    program[instr_count].c  = c;
    instr_count++;
}

/* ─── Executor ──────────────────────────────────────────────────────────── */
/*
 * execute()
 * Called once after yyparse() has loaded all instructions.
 * Runs a fetch-decode-execute loop driven by 'pc' (program counter).
 *
 * The loop terminates when pc reaches instr_count (end of program).
 * Division by zero is caught and reported.
 */
static void execute(void) {
    int pc = 0;

    while (pc >= 0 && pc < instr_count) {
        Instruction *ins = &program[pc];

        switch (ins->op) {

        /* ── Data movement ─────────────────────────────────────────────── */

        case AFC:
            /*  AFC dst val  →  memory[dst] = val  (literal constant)  */
            memory[ins->a] = ins->b;
            pc++;
            break;

        case COP:
            /*  COP dst src  →  memory[dst] = memory[src]  */
            memory[ins->a] = memory[ins->b];
            pc++;
            break;

        /* ── Arithmetic ────────────────────────────────────────────────── */

        case ADD:
            memory[ins->a] = memory[ins->b] + memory[ins->c];
            pc++;
            break;

        case SOU:
            memory[ins->a] = memory[ins->b] - memory[ins->c];
            pc++;
            break;

        case MUL:
            memory[ins->a] = memory[ins->b] * memory[ins->c];
            pc++;
            break;

        case DIV:
            if (memory[ins->c] == 0) {
                fprintf(stderr, "Runtime error: division by zero at instruction %d\n", pc);
                exit(1);
            }
            memory[ins->a] = memory[ins->b] / memory[ins->c];
            pc++;
            break;

        /* ── Comparisons  (result: 1 = true, 0 = false) ───────────────── */

        case INF:
            memory[ins->a] = (memory[ins->b] <  memory[ins->c]) ? 1 : 0;
            pc++;
            break;

        case SUP:
            memory[ins->a] = (memory[ins->b] >  memory[ins->c]) ? 1 : 0;
            pc++;
            break;

        case EQU:
            memory[ins->a] = (memory[ins->b] == memory[ins->c]) ? 1 : 0;
            pc++;
            break;

        /* ── Control flow ──────────────────────────────────────────────── */

        case JMP:
            /*
             *  JMP tgt  →  unconditional jump to instruction #tgt
             *  The target is an instruction INDEX (0-based), exactly as
             *  the compiler stored it in the coded file.
             */
            pc = ins->a;
            break;

        case JMF:
            /*
             *  JMF cnd tgt  →  jump to instruction #tgt if memory[cnd] == 0
             *  (condition is FALSE)
             */
            if (memory[ins->a] == 0)
                pc = ins->b;
            else
                pc++;
            break;

        /* ── Output ────────────────────────────────────────────────────── */

        case PRI:
            /*  PRI src  →  print memory[src] followed by a newline  */
            printf("%d\n", memory[ins->a]);
            pc++;
            break;

        /* ── Unknown opcode ────────────────────────────────────────────── */

        default:
            fprintf(stderr, "Runtime error: unknown opcode %d at instruction %d\n",
                    ins->op, pc);
            exit(1);
        }
    }
}

int  yylex(void);
void yyerror(const char *s);
%}

/* ─── Token declarations ────────────────────────────────────────────────── */
%union { int nb; }
%token <nb> INTEGER
%token NEWLINE

%%

/*
 * Grammar for coded.asm
 * ─────────────────────
 * The file is a sequence of lines.  Each line is 2, 3, or 4 integers
 * followed by a newline.
 *
 * Which rule fires for a given line is determined purely by how many
 * integers appear before the NEWLINE — Bison's lookahead handles this
 * correctly because NEWLINE is an unambiguous terminator.
 *
 *  4-integer lines  :  ADD MUL SOU DIV INF SUP EQU    (op dst x y)
 *  3-integer lines  :  AFC COP JMF                     (op a b)
 *  2-integer lines  :  JMP PRI                         (op a)
 *
 * Note: empty lines (bare NEWLINE) are silently skipped.
 */

program:
      /* empty */
    | program line
;

line:
    /* ── 4-operand instructions: opcode + 3 addresses ───────────────── */
      INTEGER INTEGER INTEGER INTEGER NEWLINE
        { store4($1, $2, $3, $4); }

    /* ── 3-operand instructions: opcode + 2 values ───────────────────── */
    | INTEGER INTEGER INTEGER NEWLINE
        { store3($1, $2, $3); }

    /* ── 2-operand instructions: opcode + 1 value ───────────────────── */
    | INTEGER INTEGER NEWLINE
        { store2($1, $2); }

    /* ── blank line (safety net) ─────────────────────────────────────── */
    | NEWLINE
        { /* skip */ }
;

%%

/* ─── Error handler ─────────────────────────────────────────────────────── */
void yyerror(const char *s) {
    fprintf(stderr, "Parse error in coded.asm: %s\n", s);
}

/* ─── Entry point ───────────────────────────────────────────────────────── */
int main(void) {
    /*
     * Phase 1 : load every instruction from coded.asm (read from stdin).
     *   ./interp < coded.asm
     */
    yyparse();
    fprintf(stderr, "[interp] %d instructions loaded.\n", instr_count);

    /*
     * Phase 2 : execute the loaded program.
     * Results appear on stdout via PRI instructions.
     */
    execute();

    return 0;
}
